### ISSUE TITLE
prefix route matching is not supported [bug]

### ISSUE THREAD

**Issue by xiaobaiskill** [gatewayorg/blue#1]
`ingress.yaml`
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-backend
  annotations:
    blue.gatewayorg.io/strip_prefix: '/api'
spec:
  rules:
    - host: blue.xiaobaiskill.cn
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: blue-dashboard-svc
                port:
                  number: 8081
```

the return is 404 when I request http://blue.xiaobaiskill.cn/api/index?start=1635843281&end=1635845081, but i request blue-dashboard-svc:8081/index?start=1635843281&end=1635845081 is ok.
